[Config file]: config_files/test_shopping/1.json
[Unhandled Error] TimeoutError('Timeout 30000ms exceeded.\n=========================== logs ===========================\nnavigating to "http://ec2-3-131-244-37.us-east-2.compute.amazonaws.com:7770/", waiting until "load"\n============================================================')
Traceback (most recent call last):
  File "/home/opadmin/llama2d_opentable/visualwebarena/run.py", line 353, in test
    obs, info = env.reset(
                ^^^^^^^^^^
  File "<@beartype(browser_env.envs.ScriptBrowserEnv.reset) at 0x7f660fcb4d60>", line 51, in reset
  File "/home/opadmin/llama2d_opentable/visualwebarena/browser_env/envs.py", line 254, in reset
    self.setup(config_file=config_file)
  File "<@beartype(browser_env.envs.ScriptBrowserEnv.setup) at 0x7f660fcb4360>", line 36, in setup
  File "/home/opadmin/llama2d_opentable/visualwebarena/browser_env/envs.py", line 205, in setup
    page.goto(url)
  File "/home/opadmin/anaconda3/envs/llama2d/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 9303, in goto
    self._sync(
  File "/home/opadmin/anaconda3/envs/llama2d/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/opadmin/anaconda3/envs/llama2d/lib/python3.11/site-packages/playwright/_impl/_page.py", line 479, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opadmin/anaconda3/envs/llama2d/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/opadmin/anaconda3/envs/llama2d/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opadmin/anaconda3/envs/llama2d/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/opadmin/anaconda3/envs/llama2d/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "http://ec2-3-131-244-37.us-east-2.compute.amazonaws.com:7770/", waiting until "load"
============================================================
